### ISSUE TITLE
Replicating Postgres tables with JSON fields

### ISSUE THREAD

**Issue by benwhite-birdiecare** [jmriego/pipelinewise-target-bigquery#2]
Hi Jose

I've had some good success using this target with the [pipelinewise-tap-postgres](https://github.com/transferwise/pipelinewise-tap-postgres) tap. Thank you for your hard work here! Works so much better than the bigquery target suggested on [singer.io ](singer.io).

However, I've come across an issue when replicating tables including JSON fields. When replicating this table:
```
CREATE TABLE benw.cards (
  id integer PRIMARY KEY,
  board_id integer NOT NULL,
  data jsonb
);

INSERT INTO benw.cards VALUES (1, 1, '{"name": "Paint house", "tags": ["Improvements", "Office"], "finished": true}');
INSERT INTO benw.cards VALUES (2, 1, '{"name": "Wash dishes", "tags": ["Clean", "Kitchen"], "finished": false}');
```

I get this error string:

```
Traceback (most recent call last):
  File "./pipelinewise-target-bigquery/bin/target-bigquery", line 11, in <module>
    load_entry_point('pipelinewise-target-bigquery==0.1.0', 'console_scripts', 'target-bigquery')()
  File "/usr/src/singer/pipelinewise-target-bigquery/lib/python3.7/site-packages/target_bigquery/__init__.py", line 423, in main
    persist_lines(config, singer_messages)
  File "/usr/src/singer/pipelinewise-target-bigquery/lib/python3.7/site-packages/target_bigquery/__init__.py", line 304, in persist_lines
    flushed_state = flush_streams(records_to_load, row_count, stream_to_sync, config, state, flushed_state)
  File "/usr/src/singer/pipelinewise-target-bigquery/lib/python3.7/site-packages/target_bigquery/__init__.py", line 359, in flush_streams
    ) for stream in streams_to_flush)
  File "/usr/src/singer/pipelinewise-target-bigquery/lib/python3.7/site-packages/joblib/parallel.py", line 934, in __call__
    self.retrieve()
  File "/usr/src/singer/pipelinewise-target-bigquery/lib/python3.7/site-packages/joblib/parallel.py", line 833, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/src/singer/pipelinewise-target-bigquery/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 567, in __call__
    return self.func(*args, **kwargs)
  File "/usr/src/singer/pipelinewise-target-bigquery/lib/python3.7/site-packages/joblib/parallel.py", line 225, in __call__
    for func, args, kwargs in self.items]
  File "/usr/src/singer/pipelinewise-target-bigquery/lib/python3.7/site-packages/joblib/parallel.py", line 225, in <listcomp>
    for func, args, kwargs in self.items]
  File "/usr/src/singer/pipelinewise-target-bigquery/lib/python3.7/site-packages/target_bigquery/__init__.py", line 386, in load_stream_batch
    flush_records(stream, records_to_load, row_count[stream], db_sync)
  File "/usr/src/singer/pipelinewise-target-bigquery/lib/python3.7/site-packages/target_bigquery/__init__.py", line 397, in flush_records
    parsed_schema = parse_schema(db_sync.avro_schema())
  File "/usr/src/singer/pipelinewise-target-bigquery/lib/python3.7/site-packages/target_bigquery/db_sync.py", line 387, in avro_schema
    "fields": [column_type_avro(name, c) for name, c in self.flatten_schema.items()]} 
  File "/usr/src/singer/pipelinewise-target-bigquery/lib/python3.7/site-packages/target_bigquery/db_sync.py", line 387, in <listcomp>
    "fields": [column_type_avro(name, c) for name, c in self.flatten_schema.items()]} 
  File "/usr/src/singer/pipelinewise-target-bigquery/lib/python3.7/site-packages/target_bigquery/db_sync.py", line 88, in column_type_avro
    items_type = column_type_avro(name, schema_property['items'])
KeyError: 'items'
```

However when running against the same table but with the field formatted as text the table uploads to BigQuery correctly.
```
CREATE TABLE benw.cards_without_JSON (
  id integer PRIMARY KEY,
  board_id integer NOT NULL,
  data ***text*** 
);

INSERT INTO benw.cards_without_JSON VALUES (1, 1, '{"name": "Paint house", "tags": ["Improvements", "Office"], "finished": true}');
INSERT INTO benw.cards_without_JSON VALUES (2, 1, '{"name": "Wash dishes", "tags": ["Clean", "Kitchen"], "finished": false}');
```

Alternatively, forcing Singer to treat the `data` field as text in the catalog file also works:
```
"metadata": [
        {
          "breadcrumb": [],
          "metadata": {
            "table-key-properties": [
              "id"
            ],
            "schema-name": "benw",
            "database-name": "datapipeline",
            "row-count": 0,
            "is-view": false,
            "selected": true,
            "replication-method": "FULL_TABLE"
          }
        },
        {
          "breadcrumb": [
            "properties",
            "id"
          ],
          "metadata": {
            "sql-datatype": "integer",
            "inclusion": "automatic",
            "selected-by-default": true
          }
        },
        {
          "breadcrumb": [
            "properties",
            "board_id"
          ],
          "metadata": {
            "sql-datatype": "integer",
            "inclusion": "available",
            "selected-by-default": true
          }
        },
        {
          "breadcrumb": [
            "properties",
            "data"
          ],
          "metadata": {
            "sql-datatype": "***text***",
            "inclusion": "available",
            "selected-by-default": true
          }
        }
      ],
      "tap_stream_id": "benw-cards",
      "schema": {
        "type": "object",
        "properties": {
          "id": {
            "type": [
              "integer"
            ],
            "minimum": -2147483648,
            "maximum": 2147483647
          },
          "board_id": {
            "type": [
              "null",
              "integer"
            ],
            "minimum": -2147483648,
            "maximum": 2147483647
          },
          "data": {
            "type": [
              "null",
              "***string***"
            ]
          }
        },
```

**Comment by jmriego** [comment]
Hi Ben,

glad to see you're finding it useful!
Thanks for opening this issue. That information was really helpful.
It seems like the postgres tap is showing the schema for that field as a struct with no fields. In that case I'd make it so that jsonb is written into BigQuery as a string. I think that's the only real option available.

I'm working on making some related changes to this target because of adding structs in BigQuery has some quirks when using DDL such as `ALTER TABLE ... ADD COLUMN`. I'll add this change as well. Shouldn't take me long

**Comment by benwhite-birdiecare** [comment]
Fantastic! Thank you Jose 👍

**Comment by jmriego** [comment]
This should be ready now. I have been able to run it with several tables and more complex data types. This jsonb type and things like recursive arrays will just be saved to BigQuery as string types. `jsonb` don't have fields that I can read from the postgres tap
Let me know if this works for you!
